export const CATEGORIES_LOAD = 'CATEGORIES_LOAD';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';

export const PRODUCTS_LOAD = 'PRODUCTS_LOAD';
export const PRODUCTS_LOAD_SUCCESS = 'PRODUCTS_LOAD_SUCCESS';
